version: '3'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:17.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DEBUG_PORT: '*:8787'
      DEBUG: 'true'
    command: ['start-dev', '--debug']
    ports:
      - 8080:8080
      - 8443:8443
      - 8787:8787
    volumes:
    - ./target/keycloak-provider.jar:/opt/keycloak/providers/keycloak-provider.jar:ro
